name:                day04
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/day04#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - split

executables:
  day04:
    source-dirs:      src
    main:             Main.hs
