name:                Day01
version:             0.1
author:              Seno

dependencies:
  - base >= 4.7 && < 5
  - mtl

executables:
  Day01:
    source-dirs:      src
    main:             Main.hs

