name:                Day11
version:             0.1
author:              Seno

dependencies:
  - base >= 4.7 && < 5
  - mtl

executables:
  Day11:
    source-dirs:      src
    main:             Main.hs

